# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gilbert's Landscaping
email: gilbertslandscaping@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gilbertslandscaping.herokuapp.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      layout: default
  -
    scope:
      path: _posts/en
    values:
      lang: en


nodes:
- text: diaspora*
  url: https://diaspora-fr.org/u/schoewilliam
- text: Github
  url: https://github.com/Schoewilliam
- text: Mozillians
  url: https://mozillians.org/en-US/u/schoewilliam/
- text: GNU Social
  url: https://status.vinilox.eu/schoewilliam